### PR TITLE
StructureLib integration

### LINKED ISSUE #9211: Mega Vac Freezer Should have minimum requirement for frost proof casing
### Your GTNH Discord Username

Hebi#2752 

### Your Pack Version

2.1.2.0

### Your Proposal

Mega Vac doesn't have any min requirements for frost proof casing, meaning
unknown-29
is an valid structure using only maint hatches and other hatches required. 

Another point is mega vac does not work with blueprints while mega ebf works, might be a good idea to integrate that too
33ef086b9a28bd2e

### Your Goal

Mega Maint Vac is such a meme kek
And blueprint should work with mega vac as well

### Your Vision

no more ridiculous structure like this lmfao
and add bp support 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by kuba6000**
StructureLib integrated to:
Electric Implosion Compressor
Bacterial Vat
Mega Vacuum Freezer
Manual Trafo
Windmill
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9211
(MVF minimum casings 0x -> 900x, that is 277 possible hatches)

### CODE REVIEW

**Comment by Dream-Master** [comment]
image

**Comment by kuba6000** [comment]
image
image

**Comment by kuba6000** [comment]
image

**Comment by kuba6000** [comment]
image

**Comment by Dream-Master** [comment]
works for me ingame

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
