### PR TITLE
Borosilicate rebalance

### LINKED ISSUE #10306: [RFC] Borosilicate Glass rebalance
### Your GTNH Discord Username

miozune#9742

### Your Pack Version

2.1.2.2qf2

### Your Proposal

Current recipes for Borosilicate Glasses:
- EV = Borosilicate Glass (HV) + 36 ingot equivalent of molten Nickel
- IV = EV + 9 Tungsten
- LuV = IV + 9 Chrome
- ZPM = LuV + 27 Iridium
- UV = ZPM + 9 Osmium
- UHV = UV + 16 Uranium 235
- UEV = UHV + 32 Europium

I suggest using main tier material and making them non-recursive, i.e.
- EV = HV + 8 Titanium
- IV = HV + 8 Tungstensteel
- LuV = HV + 8 Rhodium-Plated Palladium
- ZPM = HV + 8 Iridium
- UV = HV + 8 Osmium
- UHV = HV + 8 Neutronium
- UEV = HV + 8 ~~Bedrockium~~ Cosmic Neutronium

### Your Goal

context: https://discordapp.com/channels/181078474394566657/603348502637969419/968106506190995498

Recursive is evil, we all know. Why do we need stupid amount of Nickel for advanced UV glass?
Material tiering is also wierd. Chrome is not main material anymore, Uranium 235 is trivial at UHV (I guess).

EV-UV Glass recipes have not been changed since Bart originally added them, so it's time to change.

### Your Vision

Less tedious.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by miozune**
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10306
I'm no sure about side effect of changing existing registry name

### CODE REVIEW

**Comment by boubou19** [comment]
at best you give players new blocks at worse you need to /fml confirm the removal of the blocks

**Comment by miozune** [comment]
I can't find such command, maybe dedicated server only?
And my concern was about addons, but after second thought they won't be broken, unless they use raw string instead of accessing via `bw_realglas`

**Comment by miozune** [comment]
It seems that those names are only used for texture. Probably.

**Comment by boubou19** [comment]
if forge cannot find something in the register matching some referenced blocks on the map, you'll get a promt in solo asking if yes or no you should still load the map (yes option removing those ghost entries and any block bound to it). On server it'll wait just before loading the map until you do /fml confirm in the console (yes with the /)

**Comment by Glease** [comment]
The registry name is `BW_GlasBlocks`. Those are just texture locations.

**Comment by Steelux8** [comment]
I 100% approve of the change, but I'm not sure what will happen to the existing blocks, placed or not.

**Review by Steelux8 — APPROVED** [review]

**Pull request merged**
