### PR TITLE
Delete no longer needed dynamic pyrolyse recipe code

### LINKED ISSUE #8047: Pyrolyse oven causing server lag when wood any wood other than vanilla oak is left in the input bus
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
http://stonelegion.com
#

Tested using all LV busses, hatches, and muffler. When the machine is powered on and the pyro oven is not processing a recipe it will cause a noticeable drop in the TPS if any wood other than vanilla oak wood is left in the input bus. I admit that I did not test every wood but I tested wood from multiple mods and every single one caused a similar drop in TPS. The woods I tested are:

Minecraft:
Oak Wood 17
Spruce Wood 17:1
Birch Wood 17:2
Jungle Wood 17:3

Biomes O' Plenty:
Sacred Oak Wood 762
Cherry Wood 762:1
Redwood Wood 764

Natura:
Redwood 640:1

IndustrialCraft 2:
Rubber Wood 169

I tested this with other energy hatches such as LV, HV, and EV and they all work to reproduce this bug.
#
#### What is your GTNH Discord username?
Nrin#7237

### PR DESCRIPTION
**Pull request by D-Cysteine**
Delete the dynamic pyrolyse oven recipe generation code, which causes lag and is now redundant.

This pull request shouldn't be merged until the pull request adding the new pyrolyse recipe code is merged:
 * GTNewHorizons/NewHorizonsCoreMod/pull/197
 * Fixes GTNewHorizons/GT-New-Horizons-Modpack/issues/8047

### CODE REVIEW

**Comment by Dream-Master** [comment]
if we merge structure lib changes to the main branch this pr might be obsolete ? The changed class no longer exists.

**Comment by GlodBlock** [comment]
yeah, the pyrolyse code will move back to gt5. so maybe you need to talk with @Glease about this thing.

**Comment by D-Cysteine** [comment]
It's this pull request which deletes the file, right?
 * https://github.com/GTNewHorizons/bartworks/pull/15

So that PR will delete the TT pyrolyse oven and replace it with the original GT one? It looks like the GT code also has this dynamic recipe gen:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PyrolyseOven.java#L136-L149
so I think we just need to delete it there too. I'll send out a separate PR to do that. Thanks for pointing this out! Didn't realize that there was another instance of this code.

As for this PR, it can be closed if https://github.com/GTNewHorizons/bartworks/pull/15 gets merged, as it will no longer be applicable. If it will be a while before https://github.com/GTNewHorizons/bartworks/pull/15 gets merged, then it may make sense to merge this PR first, to get rid of the laggy code so players can stop lagging.

**Comment by GlodBlock** [comment]
in fact, glease is rewriting all gt mulits in his pr : https://github.com/GTNewHorizons/GT5-Unofficial/pull/551
so i think he just make these changes in his pr.

**Comment by D-Cysteine** [comment]
I think that PR is just making structure changes though, so I'm not sure if it makes sense to also include recipe changes in it? But yeah, if Glease wants to include these changes in that PR, then we don't need a separate PR. I already made one: https://github.com/GTNewHorizons/GT5-Unofficial/pull/608, but we can close it if the changes get included in Glease's.

**Pull request closed without merging**
