### PR TITLE
Change voltage in blast furnace recipes

### PR DESCRIPTION
**Pull request by kuba6000**
See https://github.com/GTNewHorizons/bartworks/pull/36
Changes:
bartimaeusnek - 1920 EU
rhodium plated palladium - 480 EU
ruridit - 480 EU
hdcs - 7680 EU
ademic steel - 1920 EU

### CODE REVIEW

**Comment by iouter** [comment]
I suggest my formula:
image
after this change, ruridit's recipe is LuV, about 156.6s; high durability compound steel's recipe is UIV, about 349.1s.

but this will only make these recipes more reasonable, and players can't get free parallel rewards again(when you use the mega ebf).

**Comment by GTNH-Afx237v7** [comment]
What do you mean by „can’t get free parallel rewards again“?

**Comment by GlodBlock** [comment]
no, the voltage must be set manually because it's used to gate or balance recipe, set these things automatically will cause silly recipes.

> I suggest my formula:
> image
> after this change, ruridit's recipe is LuV, about 156.6s; high durability compound steel's recipe is UIV, about 349.1s.
> 
> but this will only make this recipes more reasonable, and players can't get free parallel rewards again(when you use the mega ebf).

smelt a ingot for 100+s in luv voltage is a disaster in luv. this is a good example of the silly recipe.

**Comment by iouter** [comment]
> What do you mean by „can’t get free parallel rewards again“?

the voltage of the original recipe is 120eu/t, and mega ebf have 256 parallel (but I don't think most people will make the mega ebf at LuV)

**Comment by iouter** [comment]
> no, the voltage must be set manually because it's used to gate or balance recipe, set these things automatically will cause silly recipes.

there's nothing wrong with automatically setting the recipe time, and silly recipes can have additional manual set.

> smelt a ingot for 100+s in luv voltage is a disaster in luv. this is a good example of the silly recipe.

I agree. I think it's more reasonable to divide time by two. the time of ruridit is about 63.2s, rhodium plated palladium is 70.3s when argon is used.

**Comment by kuba6000** [comment]
I think automatic voltage calculation is a terrible idea
I also forgot to write the changes I made so here they are:
bartimaeusnek - 1920 EU
rhodium plated palladium - 480 EU
ruridit - 480 EU
hdcs - 7680 EU
ademic steel - 1920 EU

**Comment by Prometheus0000** [comment]
So, what are you changing them from, and why?

**Comment by Pxx500** [comment]
> So, what are you changing them from, and why?

https://github.com/GTNewHorizons/bartworks/pull/36

**Comment by kuba6000** [comment]
> So, what are you changing them from, and why?

I am changing them from the default voltage of 120 EU because in the previous pull request #36 I accidentally made them faster to smelt

**Comment by Prometheus0000** [comment]
So they were originally X, then 120, now some numbers you listed. Are these numbers the same as X, which is what you changed them from?

**Comment by Pxx500** [comment]
> So they were originally X, then 120, now some numbers you listed. Are these numbers the same as X, which is what you changed them from?

Only the smelting time got changed and now he's changing voltage to match total eu

**Comment by Prometheus0000** [comment]
Why would you match the total EU over matching the voltage? That changes the tier of the ingots, which isn't desired. It should be the same tier, then match the time to get the total EU. Or reduce it if they have crazy numbers.

**Comment by Pxx500** [comment]
> Why would you match the total EU over matching the voltage? That changes the tier of the ingots, which isn't desired. It should be the same tier, then match the time to get the total EU. Or reduce it if they have crazy numbers.

But why are they smeltable at MV while being unlocked at IV?

>match the time

bartworks calculates time automatically based off ingots weight for some reason, so the voltage is being changed to keep time as close to original as possible (rounded down)

**Comment by Prometheus0000** [comment]
So these were all MV before? Why not make them EV/IV and adjust the time? Instead of adjusting the voltage?

**Comment by Pxx500** [comment]
> So these were all MV before? Why not make them EV/IV and match the time? Instead of matching the voltage?

We've calculated the closest perfect overclock to the original time and changed the voltage so both eu cost and time are as close to original as possible, we can't change the time since it's calculated automatically

**Comment by Prometheus0000** [comment]
I'd just like to say that I think setting heat, voltage, or time automatically is weird to begin with. At least for the EBF.

**Comment by Pxx500** [comment]
> I'd just like to say that I think setting heat, voltage, or time automatically is weird to begin with. At least for the EBF.

Well it's so weird that we didn't know that it will break something until after the merge

**Comment by Dream-Master** [comment]
Coils need to gate stuff but voltage have to. Ok we need to discuss about voltage change for all material but this change is a better one then the atom weight thing

**Review by GlodBlock — APPROVED** [review]

**Pull request merged**
