### PR TITLE
Add Compat for bartworks and Cell-less PA change

### PR DESCRIPTION
**Pull request by BlueWeabo**
This is going to be required if this, 
* https://github.com/GTNewHorizons/GT5-Unofficial/pull/1346, 

gets accepted after stable

Allows BW compact to the new recent PA change, all tested with multiple dusts and machines.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@BlueWeabo did you run spotless apply ?

**Comment by BlueWeabo** [comment]
Yes spotless was ran. It is just failing as the PR required is not merged as it needs a new recipe map variable.

**Comment by Dream-Master** [comment]
@BlueWeabo ah ok didnt see

**Comment by BlueWeabo** [comment]
@eigenraven can you also review this? as it is also needed. Updating dependencies should make it work. I have tested it multiple times so it should work. I saw you reviewed the other 2 PRs.

**Comment by eigenraven** [comment]
Yeah I was just waiting for the dependencies to get updated, so it doesn't get merged by accident with a broken build by MergeMasterXXL :P

**Comment by Dream-Master** [comment]
@eigenraven merge it i do the rest

**Review by eigenraven — APPROVED** [review]

**Comment by Dream-Master** [comment]
@BlueWeabo i will do tags now

**Comment by eigenraven** [comment]
@Dream-Master you should push changes to the PR branch, not merge and then push changes to master

**Comment by Dream-Master** [comment]
ok next time :)

**Pull request merged**
