### PR TITLE
Electric Implosion Compressor Bug fix

### PR DESCRIPTION
**Pull request by kuba6000**
Fix issue where EIC sometimes stops when supplied with 2 UHV energy hatches

### CODE REVIEW

**Comment by repo-alt** [comment]
Now it will work only with 2 working (supplied) energy hatches - is it intended? (I never used that multiblock myself)

**Comment by kuba6000** [comment]
yes

**Review by repo-alt — APPROVED** [review]
Ok then.

**Comment by Skiftcha** [comment]
> is it intended?

> yes

is it? it is commonly used with UEV energy hatches installed, when only one of them supplied with energy (usually from bottom)
so this is more comfortable to wire and more reliable to maintenance issues (2 UHV hatches do not provide extra amps for 10% penalty)

**Comment by kuba6000** [comment]
> > is it intended?
> 
> > yes
> 
> is it? it is commonly used with UEV energy hatches installed, when only one of them supplied with energy (usually from bottom)
> so this is more comfortable to wire and more reliable to maintenance issues (2 UHV hatches do not provide extra amps for 10% penalty)

From my testing it was sometimes working with UHV hatches and sometimes stopping randomly. I just fixed it to always work by draining two hatches evenly. Also there are two hatches needed for structure and should be powered, not just one. As illustrated by this beautifully crafted image:
image

**Pull request merged**
