### PR TITLE
Change Large liquid air input hatch to all fluids

### PR DESCRIPTION
**Pull request by LewisSaber**

### CODE REVIEW

**Comment by kuba6000** [comment]
Recipe should also be changed
image

**Comment by Pxx500** [comment]
Why do you need this change?

**Comment by LewisSaber** [comment]
for extreme heat exchanger

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9951

**Comment by Pxx500** [comment]
It should be an output hatch...

**Comment by LewisSaber** [comment]
it needs a lot of water too

**Comment by Pxx500** [comment]
You definitely don't need a giant hatch amount of water
1l of water gives 160L of steam, assuming you are going to use giant hatch as an output  then to generate full hatch every second then 1ZPM hatch is more that enough to supply water and you can also use 3LUV

**Comment by Pxx500** [comment]
Actually now that I've seen the recipes this PR makes sense, but definitely not for all liquids.

**Comment by GTNHAfx237v7** [comment]
There is a giant output hatch accepting any fluid, so why not allow the giant input hatch any fluid?

**Comment by Pxx500** [comment]
It's too cheap and would be used everywhere I guess, output hatches are just impractical sometimes

**Comment by GTNHAfx237v7** [comment]
Well structures that require a certain hatch type are defined (like fusion), everything else can use all sizes iirc. And 64HV is not super cheap early on. But I get your point, at some point making 64HV is easier than Setting up PBI chain and having to use ZPM assembler.

**Pull request closed without merging**
