### PR TITLE
Circuit Assembly Line now uses structureLib

### PR DESCRIPTION
**Pull request by matt-159**
I wanted vertical CAL's so now there are vertical CAL's.
The texture of the CAL doesn't rotate properly

### CODE REVIEW

**Comment by matt-159** [comment]
It's not actually forming right now. trying to figure out why

**Review by Glease — CHANGES_REQUESTED** [review]
Description says EV+ tier glass, but the structure you have defined allow reinforced glass only. This might be problematic.

**Comment by matt-159** [comment]
image
image

**Review by Glease — APPROVED** [review]
This works for now I guess 😢

**Pull request merged**
