### PR TITLE
Switched from internal OC calc function to new GT_OverclockCalculator

### PR DESCRIPTION
**Pull request by minecraft7771**

### CODE REVIEW

**Review by Glease — COMMENTED** [review]
What are we trying to catch really with those try catch?

**Comment by minecraft7771** [comment]
The getters can throw an exception if the calculator isnt set up correctly. so I have to wrap them in try-catch so intelliJ stops complaining.

**Comment by miozune** [comment]
Remove `throws` clause from getter methods then

**Comment by minecraft7771** [comment]
@BlueWeabo

**Comment by BlueWeabo** [comment]
> Remove `throws` clause from getter methods then

Should I give Max Values then instead? because mitch recommended me to do something when its not done correctly.

**Review by Glease — APPROVED** [review]

**Pull request merged**
