### PR TITLE
allow CAL to accept more circuit recipes

### LINKED ISSUE #8060: High Energy flow circuit only have circuit assembler recipe
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to make a circuit assembly line (CAL) for the high energy flow circuit (added by the core mod, and used in the recipe of the active transformer from tectech, it's only use case), but the high energy flow circuit only has a recipe in the circuit assembler. I suggest to add a recipe for it in the CAL, as opencomputer's microchips are also added to the CAL.

### PR DESCRIPTION
**Pull request by GlodBlock**
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8060

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Does this automatically add recipes to the CAL, or only allow adding new recipes? Because there's probably a number of circuits that shouldn't go through the CAL.

**Comment by GlodBlock** [comment]
it will add recipe automatically. what kind of circuits shouldn't be added? i can make a blacklist for them

**Comment by Prometheus0000** [comment]
Does it just grab any item with 'circuit' in the name, or is there another condition? Will it start adding chisel blocks for example? Like being made in the SB CA?

**Comment by GlodBlock** [comment]
the item must have 'circuit' in unloaclized name and have a circuit assembler recipe. CAL generate its recipe from the sb circuit assembler recipes so it can't add 'new' recipes to the sb recipe collection. chisel blocks don't have circuit assembler recipe so they won't be added

**Comment by Prometheus0000** [comment]
I see, I thought it would just grab anything.

Bio and wetware circuit boards should be forbidden.
The questionable ones would be the forestry and RC circuits. I'd like to hear if other people think they should be allowed or not.

**Comment by repo-alt** [comment]
I think Forestry/RC/OC circuits don't matter at all

**Comment by Prometheus0000** [comment]
OC ones weren't picked up searching for 'circuit' in NEI, so they wouldn't be added anyway.

**Comment by GlodBlock** [comment]
bio and wetware circuit boards don't have `circuit` in unloaclized nor oredict name, so don't worry about them.
as to forestry/rc ones, i think they are ok to be made in cal

**Comment by Prometheus0000** [comment]
So it has to be uncapitalized? That's not what the code looks like? They're made in the CA, and have 'Circuit' in the name, why wouldn't they be picked up?

**Comment by GlodBlock** [comment]
no, both `circuit` and `Circuit` will be accepted

**Review by Dream-Master — APPROVED** [review]

**Comment by GlodBlock** [comment]
> They're made in the CA, and have 'Circuit' in the name, why wouldn't they be picked up?

their name are `gt.metaitem.03.32006.name` and `gt.metaitem.03.32105.name`

**Pull request merged**
