### PR TITLE
add integrated circuit to auto mix recipe

### PR DESCRIPTION
**Pull request by GlodBlock**
add an option to add integrated circuit to auto generated mix recipes. currently all auto generated mix recipes don't use the circuit, there is going be tons of recipe conflict when bw alloy become more.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@GlodBlock why T_TileEntity_MegaProcessingArray.java  is removed ? Are you mixed up branches ?

**Comment by GlodBlock** [comment]
glee8e make some changes to the PA in gt5u and that break the Mage PA in bw. i have to remove it otherwise it will fail to complie. i also have talked about this thing with him in discord and he said it's ok to remove it since it is WIP and we are going to have Obama in future.

**Comment by Glease** [comment]
Obama is irrelavent here. I suggest to remove it purely because the thing doesn't work at all and it isn't in the game anyway.

**Comment by Dream-Master** [comment]
@mitchej123 you pr https://github.com/GTNewHorizons/bartworks/pull/33 already in this one

**Comment by mitchej123** [comment]
Yes, but I'm not familiar enough with the other stuff in this PR to say yay or nay, and nobody has approved it.  It's currently holding me up :)

**Comment by Dream-Master** [comment]
@Glease

**Review by Glease — APPROVED** [review]

**Pull request merged**
