### PR TITLE
Singlemuffler

### PR DESCRIPTION
**Pull request by bombcar**
This is in reference to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8883

It forms, but there is costing to be discussed

### CODE REVIEW

**Comment by Dream-Master** [comment]
i am against this change. Why we not make a new block some super muffler

**Comment by bombcar** [comment]
> i am against this change. Why we not make a new block some super muffler

That would be needed if we go this route - but it's possible the MEBF is iterating over every muffler every tick. If so, this will not be necessary and can be closed.

**Comment by Dream-Master** [comment]
sure the muffler need to emit more pollution because this mega ebf is huge and fast

**Comment by Dream-Master** [comment]
how much muffler one Mega EBF need ?

**Comment by bombcar** [comment]
> how much muffler one Mega EBF need ?

169

without that it would not be able to clear pollution ... heh (this change would give it only one :D )

**Comment by boubou19** [comment]
looked at the code, and you allow additionnal hatches in addition of the central hatch. Why? a single muffler hatch is enough to tank the max pollution rate of 102400 gibbl/s. Also, reducing it to one make it looks like it's ridiculous imo, why not 3x3 or 5x5?

**Comment by bombcar** [comment]
> looked at the code, and you allow additionnal hatches in addition of the central hatch. Why? a single muffler hatch is enough to tank the max pollution rate of 102400 gibbl/s. Also, reducing it to one make it looks like it's ridiculous imo, why not 3x3 or 5x5?

That was to prevent existing ones from deforming. 3x3 or 5x5 would be likely better - but if the actual lag is the iteration then it wouldn't be necessary.

**Comment by bombcar** [comment]
Actually as it currently stands it just lets you choose to muffler or not for each block on the top, so I suppose you could draw a face or write dirty words in mufflers on the top ...

**Comment by bombcar** [comment]
image

I agree it looks silly. If we ended up making a mega muffler it should do the turbine texture thing

**Comment by Sphyix** [comment]
To be honest I would gladly accept how silly it looks if we can reduce useless load on the server

**Pull request closed without merging**
