### PR TITLE
Do not overwrite localized name with default name

### PR DESCRIPTION
**Pull request by Glease**

### CODE REVIEW

**Comment by repo-alt** [comment]
Is it known what was the original reason for that code?

**Comment by Glease** [comment]
@bartimaeusnek Hi, can you still recall why you were doing this? Currently this is causing items/blocks that can be properly localized without bartwork to have non localizable parts, e.g.
localization_problem

**Comment by Glease** [comment]
Bart says ok if it works in game. see #github-discussion on discord.

**Comment by boubou19** [comment]
https://discord.com/channels/181078474394566657/401118216228831252/860875117990641694

**Pull request merged**
