### PR TITLE
Make aqua regia more realistic

### PR DESCRIPTION
**Pull request by iouter**
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7844

aqua regia should be able to recycle perfectly after the change.

### CODE REVIEW

**Comment by GlodBlock** [comment]
it is an evil and cursed change

**Comment by ArtherCasan** [comment]
realistic improvement

**Comment by Dream-Master** [comment]
why evil ?

**Comment by GlodBlock** [comment]
unlike other recipe change which only needs players to recode their ae2 pattern, this change will break most people's platline setup.

**Comment by Dream-Master** [comment]
each update we break stuff. Will check later on my computer. Can't view the change very well on my phone.

**Comment by GTNH-Afx237v7** [comment]
This adds even more chlorine and hydrogen use to the platline. Please no

**Comment by iouter** [comment]
I didn’t decide whether to produce hydrochloric acid or dilute hydrochloric acid. dilute hydrochloric acid is a more reaslistic choice, but the speed of distilling dilute hydrochloric acid will not keep up with the speed of platinum line LCR. choosing hydrochloric acid will remain the same as the original one, it can be recycled, and no distillation is required.
and i found i forgot to blance the number of cells, will be fixed after the decision is made.

**Comment by iouter** [comment]
> This adds even more chlorine and hydrogen use to the platline. Please no

it can be recycled. no need to produce more hydrochloric acid.

**Comment by boubou19** [comment]
a change that'll break platline setups just for the sake of realism. Where's the fun in rebuilding your totally working setup just because someone wants more realism... Did you at least checked on the whole platline all the impacts of such change?

**Comment by iouter** [comment]
aqua regia can only be used for platinum.

**Comment by GlodBlock** [comment]
people have to add another distillery or a stack of it to distill the damn dilute hydrochoric acid in their platline setup for no reason but this "realistic" pr.

**Comment by iouter** [comment]
A chemistry expert thought that the output was not dilute hydrochloric acid, and considering that it is not good to use too many distillery, so it was changed to hydrochloric acid.

**Comment by Pxx500** [comment]
This change makes sense but aqua regia shouldn't be 100% recyclable to keep things balanced. HCl can be 100% recyclable though, just not nitric acid.

**Comment by bombcar** [comment]
Is it possible to 

1. make this a NEW recipe under a different (new) circuit
2. HIDE the existing recipe from NEI but allow it to continue to work
or
3. make this a new recipe with new circuit but a benefit compared to the old method whilst leaving the old? Perhaps reduced power usage/time or something

**Comment by iouter** [comment]
of course it is possible.
but the current recipes only needs to replace dilute sulfuric acid with hydrochloric acid, without additional automation settings, and this will add a strategy of replacing hydrochloric acid with nitric acid and dilute nitric acid. (but I don’t think anyone will use it).
as for the benefits, the only one is that the speed of making aqua regia is twice as fast as the original. and because I didn’t add any disadvantages, so I don’t want to add more benefits.

**Pull request closed without merging**
