### PR TITLE
Circuit Assembly Line enhanced tooltip

### PR DESCRIPTION
**Pull request by kuba6000**
image
image
image

### CODE REVIEW

**Comment by chochem** [comment]
certainly an improvement :)

could you maybe make it more clear that it only takes one energy hatch?

**Comment by kuba6000** [comment]
> certainly an improvement :)
> 
> could you maybe make it more clear that it only takes one energy hatch?

Yes, changed. Is that good enough ?
image

**Comment by miozune** [comment]
Can you add mention to perfect overclock like LCR does? :)

**Comment by kuba6000** [comment]
> Can you add mention to perfect overclock like LCR does? :)

Done

**Review by miozune — APPROVED** [review]

**Pull request merged**
