### PR TITLE
Buffed Oganesson in Fusion to Beat Replication

### PR DESCRIPTION
**Pull request by Steelux8**
- Changed the Oganesson fusion recipe to reduce total EU cost from around 750M EU to 215M, which matches the EU cost in the replicator multi.
- Changed the recipe time to make the crafting faster, but not nearly as fast as the replicator multi.

Oganesson is considered by everyone as an element made with fusion, and then replicated from that point on. This is because making more from fusion is very expensive. I have made the math between both options, and the numbers are roughly as follows:

- Replicating in perfect conditions (only LV replicators) is around 200M per bucket;
- Replicating in a UHV replicator multi from GT++ is around 213M per bucket, very fast but the setup is expensive to build;
- Using the fusion recipes needs extra inputs like Plutonium 239, and is around 750M per bucket;
- With this change, the energy cost in fusion will be around 226M per bucket, close to the cost of the replicator multi but a lot slower;
- The speed of fusion is 166s per bucket with one t3 reactor doing the Og recipe, while the replicator multi does it at 0,7s per bucket.

I'm aware that the GT++ multis for this are broken, which needs to be fixed. I got the numbers for that setup from someone who had a quickfix made. The balance of those can be discussed after this PR, since removing replication and leaving fusion as-is will make Og much more expensive than it currently is.

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
Honestly Og replication should just be disabled. We all know it's busted and people will still use it because of the opportunity cost of just using that fusion for making EU and dumping it into UUM.

**Comment by Steelux8** [comment]
> Honestly Og replication should just be disabled. We all know it's busted and people will still use it because of the opportunity cost of just using that fusion for making EU and dumping it into UUM.

I don't disagree, but I think fusion should be buffed and replicating nerfed, before replicating is removed completely. At least one dev release between the two so that people can switch over without losing their Og source.

**Comment by Dream-Master** [comment]
replication should be more complex. Maybe a new Multiblock not that ass cheap single Block.

**Comment by Steelux8** [comment]
> replication should be more complex. Maybe a new Multiblock not that ass cheap single Block.

There's already a GT++ replication multiblock, and it's incredibly fast, as I mentioned in the PR description.

**Comment by Dream-Master** [comment]
maybe we nerf this block/multi and remove the single block stuff.

**Comment by Steelux8** [comment]
Yes, but the fusion recipes are too expensive anyways. Nobody uses them at this cost.

**Comment by chochem** [comment]
Buffing oganesson fusion has been discussed and requested for a long time. Great to see it is happening. 

Ideally replication should never be the best option for any material as its not very interesting and the same for everything.

**Comment by Sphyix** [comment]
Just to explain it here aswell for ppl that didn't follow discussion on discord:
first, people always use the most cost effective method of getting stuff, or in case there isn't much difference, the fastest or easier to setup.
Removing an alternative because the worst way of making it isn't being used is not a smart move, it should never be done.

Now, speaking of Og, there are 2 uses for it that I know of, smelting of ingots (no one does that) and speeding up void miners.

The new replication, with the current cost of Og is probably going to allow players to use it for smelting, as the output with enough power dumped in UUM is going to be 1 bucket/tick or greater (power dump is huge tho, like UXV or higher on UUM)

Now, I see an issue with this, the amount needed for smelting is crazy high compared to the amount needed for void miners.
So with the high volumes we have now of Og, void miners use so little it doesn't even matter anymore.
I don't think void miner amount required should change, since there are 2 other fluids used, and keeping them the same is good.
The amount for ingots should change to something a LOT lower.
With this, obviously, fusion and replication should both yield a LOT less, without changing the overall cost of what Og is used for.

So idea would be to completely realign production and consumption of Og, based on current cost, keeping them similar to what they are now.
Then, to encourage fusion usage, make fusion yield more at a reduced cost, so people prefer a more complicated setup in exchange of a lower overall cost.

**Comment by Steelux8** [comment]
> Now, I see an issue with this, the amount needed for smelting is crazy high compared to the amount needed for void miners. So with the high volumes we have now of Og, void miners use so little it doesn't even matter anymore. I don't think void miner amount required should change, since there are 2 other fluids used, and keeping them the same is good. The amount for ingots should change to something a LOT lower. With this, obviously, fusion and replication should both yield a LOT less, without changing the overall cost of what Og is used for.

On the contrary, I think both the EBF and VM values should be changed, one lowered and the other raised to meet at a sort of middle ground. Og production can then be balanced for both purposes. The other noble gases are also much simpler to automate at good speeds, with the new planetary siphon, which means that huge air DT setups or nuclear fission breeders aren't required to automate the expensive noble gases anymore.

**Comment by Eranicus** [comment]
As for Og. replication i have to agree it is too easy to make compared to fusion.

As for replication in general I have the following setup - 28 mass fabricators and currently 1 elemental dublicator multi. All this setup requared  really a lot of resourses to build and approx. 30 mil eu to maintain. Produsing around 3.6 mil. uu-matter per hour which is not alot if you look at material replication prices and amount of resourses you need at UV-UHV+

and elemental dublicator multi recipe registration is broken in 2.3qf+ 

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10370

**Comment by Sphyix** [comment]
> On the contrary, I think both the EBF and VM values should be changed, one lowered and the other raised to meet at a sort of middle ground.

I have no idea about the siphon, tiering or how it works. If neon and krypton are easier to get at LuV and ZPM, then yes void miner fluid value needs to be raised.

Anyway, the complete rework is a good direction to take, I don't think this PR is the right direction for Og as it's just a band-aid for a bigger problem that exists with it.

**Comment by Steelux8** [comment]
> > On the contrary, I think both the EBF and VM values should be changed, one lowered and the other raised to meet at a sort of middle ground.
> 
> I have no idea about the siphon, tiering or how it works. If neon and krypton are easier to get at LuV and ZPM, then yes void miner fluid value needs to be raised.
> 
> Anyway, the complete rework is a good direction to take, I don't think this PR is the right direction for Og as it's just a band-aid for a bigger problem that exists with it.

This is just one of the steps of the rework. As it is, Oganesson fusion is just too expensive.

**Comment by Dream-Master** [comment]
i think we should rewrote the replication code to make it more balance. UUM is a very old methode for it and i like to see some kind of Multiblock for it instead od this stupid single block.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
