### PR TITLE
ABS fluid output free from bart recipe reaper 

### PR DESCRIPTION
**Pull request by lc-1337**
now ABS to able make molten iridium, osmium, platinum, ruthenium, rhodium
This PR add only 4 ABS recipe

Ruthenium from Osmium/Sheldonite purified ore
image

Ruthenium from Iridium/Platinum purified ore
image

### CODE REVIEW

**Comment by miaowwwwww** [comment]
is there any other recipes effected besides platline metals?

**Comment by Hikari1nVoid** [comment]
please remove these recipes as they are potential platline skips.

**Comment by lc-1337** [comment]
These recipes came from GT++, is better to delete them in GT++ or i should make specific cleaner only for this recipes in BW?

**Comment by chochem** [comment]
yea, best to remove them in gt++. I guess I can quickly do that.

**Comment by chochem** [comment]
btw, this adds 3 more recipes: palladium, rhodium, ruthenium dust to molten fluid. But those can stay and are the intended target here.

**Review by chochem — APPROVED** [review]
the 4 ruthenium skips are resolved on the gt++ end, so this looks fine now.

**Comment by Dream-Master** [comment]
ok i give it a go

**Pull request merged**
