### PR TITLE
Change mass calculation to match gregtech way

### LINKED ISSUE #8366: Bartworks dusts take too long to centrifuge
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I wanted to use bartworks ores
#
#### What happened instead? (Attach screenshots if needed)
They clogged my entire ore system
#
#### What do you suggest instead/what changes do you propose?
- Lower time it takes to centrifuge bartworks dusts, some take even 400 sec@LV
- Add option to wash them in a simple washer
- Add option to wash them

Something else maybe?
#
#### What is your GTNH Discord username?
Pxx500#6984

### PR DESCRIPTION
**Pull request by kuba6000**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8366

### CODE REVIEW

**Comment by GlodBlock** [comment]
but is it an intended design by bart?

**Comment by kuba6000** [comment]
It was probably intentional, but it's neither good nor balanced

**Review by GlodBlock — APPROVED** [review]

**Comment by ScriptedPiky** [comment]
This may have unintended interactions with the EBF recipes he made, though I'm unsure if this will also affect the EBF material recipes. Will be something to keep an eye out for

**Comment by Pxx500** [comment]
> This may have unintended interactions with the EBF recipes he made, though I'm unsure if this will also affect the EBF material recipes. Will be something to keep an eye out for

We've found the changes and they are not that important, Bartimaeusnek dust smelting time went down from 4950 seconds to 450 seconds and some alloys have faster tools but nothing gamebreaking (afaik).

**Comment by ScriptedPiky** [comment]
> We've found the changes and they are not that important, Bartimaeusnek dust smelting time went down from 4950 seconds to 450 seconds and some alloys have faster tools but nothing gamebreaking (afaik).

Are the recipe voltage tiers still MV? I would imagine that if it went from 4950 to 450 and still had MV voltage requirements, LuV+ smelting would end up becoming a breeze in difficulty, heh

**Comment by GlodBlock** [comment]
a potential way to solve it is to set the smelt voltage manually, it is unrealistic to expect it to generate reasonable voltage automatically, so a new `Werkstoff.GenerationFeatures` to set voltage would be good

**Comment by Pxx500** [comment]
The question is whether we should do anything since afaik bartimaeusnek ingots are useless and have no important recipes, only the dust is used in centrifuge, well most bartworks alloys have no use atm so maybe there won't be a problem with that? Can be solved and rebalanced later after they have a purpose though

**Comment by GlodBlock** [comment]
no, all bart's alloys will be affected.
use ruridit as an example.
this is the old recipe
image
this is the changed recipe
image

**Comment by Prometheus0000** [comment]
Why is this an MV recipe? You can't even get it until EV/IV. Why show crazy numbers that won't ever be used, and make the calculations harder?

**Comment by Pxx500** [comment]
> use ruridit as an example.

I forgot bartworks has some useful alloys, my bad
We will do something about that in a few hours

**Comment by Pxx500** [comment]
> Why is this an MV recipe? You can't even get it until EV/IV. Why show crazy numbers that won't ever be used, and make the calculations harder?

Probably to make everything automatically and don't bother with doing things like recipe time manually because resources are gated

**Comment by iouter** [comment]
before:
V$~%V3DBTP60CE09X30}~DL
after:
HXR`${@(1TI$7WGKR2BNA(U

**Comment by Pxx500** [comment]
What material is that?

**Comment by GTNH-Afx237v7** [comment]
Looks like high durability compound steel

**Comment by iouter** [comment]
> Looks like high durability compound steel

yes

**Pull request merged**
